### ISSUE TITLE
load_hinge path does not allow for spaces

### ISSUE THREAD

**Issue by Simard302** [Pranavkhade/PACKMAN#33]
When the path in your .hng file contains any whitespace, the  `line=i.strip().split()` in `utilities.load_hinge` splits the line into a list that is longer than 3. Afterwards, the `HNGinfo[ line[0]+'_'+line[1] ]=[float(j) for j in line[2].split(':')]` becomes irrelevant because the first, second, and third elements of `line` are not as intended

**Comment by Pranavkhade** [comment]
Thank you for posting this. This issue has been fixed for the GUI in this pull request: https://github.com/Pranavkhade/PACKMAN/pull/32. I am waiting on my colleague's response on it.

I will fix it completely, but meanwhile, please continue to use files without spaces.

Thanks,
Pranav

**Comment by Pranavkhade** [comment]
This issue has now been fixed with version 1.4.5 #32
