### ISSUE TITLE
Long PDB / PDBx - MMCIF : unable to perform an analyze

### ISSUE THREAD

**Issue by Kambeiz** [Pranavkhade/PACKMAN#35]
Dear maintainer, i encounter a problem using PACKMAN

**Client Used :** PACKMAN GUI provided through pip installation

Error encountered with PDB :
![image](https://user-images.githubusercontent.com/58467144/171167247-710cb70c-b83f-4b43-9611-1a12e63b82db.png)

Error encountered with CIF : 
![image](https://user-images.githubusercontent.com/58467144/171167247-710cb70c-b83f-4b43-9611-1a12e63b82db.png)
![image](https://user-images.githubusercontent.com/58467144/171169213-9df62f4e-6047-48c2-b51a-8c969c0c5ccb.png)
In both case, i don't obtain any result 

Parameters used on the GUI : default 

At first i thought it was the PDB or CIF file i was providing that was with a wrong formatting, so i tried various mean for saving my original file using different software (pdb_tools, pdb2cif, pymol, vmd..). 
I also tried to split my structure and kept one monomer, but it doesn't work either. 

I tried to use a similar structure (size wise) in CIF, it seemed to work. 

So i come in your direction seeking help

Kind Regards

**Comment by Pranavkhade** [comment]
Hello,

Thank you for reporting this potential error. Can you please provide me with a PDB file that you were using? (if that is alright)

Thanks,
Pranav

**Comment by Kambeiz** [comment]
Hello,

Here is a pdb file where i encounter the error, this one have been formatted through the use of vmd option "saving coordinates file"
https://cloud.univ-grenoble-alpes.fr/index.php/s/sqp7mknp5GKAnTc 

Thank you for your time
Nagi

**Comment by Pranavkhade** [comment]
The reason why this is failing is that PACKMAN requires Atom IDS to be integers (this follows guidelines on: http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM) whereas, there are lines in the provided files that use string in the atom ids (check line number 100001). This is making PACKMAN to reject the file.

I do not think I will be making an exception to make atom ids as strings as it doesn't follow the convention. Please convert the atom IDs to integers using scripts and it will work like any other PDB file.

Thank you. Sorry for the delay in the response as I have joined a full-time job.
Pranav
