### ISSUE TITLE
alpha shape

### ISSUE THREAD

**Issue by unverciftci** [Pranavkhade/PACKMAN#9]
This is not an issue but a question. I just need the alpha shape, how can I extract it? Thank you in advance.

**Comment by Pranavkhade** [comment]
Hello @unverciftci. Thanks for your question. The answer depends on the nature of the data you want in return.

1. If you want just the alpha shape of the given protein (edges and faces) you can use the --generateobj  option in the code and you get the alpha shape in .obj file format.

2. If you need the alpha shape along with the residue information, you read [https://github.com/Pranavkhade/PACKMAN/blob/master/packman/apps/predict_hinge.py] The 'SelectedTesselations' object has all the information about the alpha shape.
Steps: 1. 'import predict_hinge from packman.apps' 2. provide appropriate parameters, including alpha 3. Access the alpha shape stored in 'SelectedTesselations' object.

**Comment by unverciftci** [comment]
Hi Pranavkhade, 
Thank you for your reply. I try but get an empty file. I think this is the case for the web server as well. 
Could you please check it and tell me your example command?

**Comment by Pranavkhade** [comment]
I tested it and it is giving me the output file. The reason you are getting an empty file might because you are choosing the alpha value which is too low or not specifying the chain.

My trial parameters: 
1. PDBID: 6LU7 (or any other PDBID)
2. Chain: A
3. Alpha: 4.2

**Comment by unverciftci** [comment]
Many thanks, it works!
